# frozen_string_literal: true
source 'https://rubygems.org'
ruby '2.6.3'

gem 'rspec'
gem 'bundler'
gem 'selenium-webdriver'
gem 'sinatra'
gem 'uri-handler'
gem 'net-http-persistent'
gem 'minitest'
gem 'rubysl-base64'
gem 'simplecov'
gem 'require_relative'
gem 'activerecord', '~> 4.2.2'
gem 'strftime', '~> 1.0.0'
gem 'send-keys', '~> 0.1.0'
gem 'factory_girl', '~> 4.0'
gem 'rspec-rails', '~> 3.3.3'
gem 'pry', '~> 0.10.2'
gem 'chromedriver-helper', '~> 1.0'
gem 'headless'
gem 'rails', :group=>:test
gem 'rails_config', '0.4.2'
gem 'jquery-rails'
gem 'watir'
gem 'json'
gem 'webdriver-user-agent', '~> 7.4'
gem 'rb-readline', '~> 0.5.3'
gem 'rspec-core', '~> 3.3', '>= 3.3.1'
gem 'rack', '~> 1.6', '>= 1.6.5'
gem 'typhoeus', '~> 1.1'
gem 'allure-rspec', '~> 0.6.9'
gem 'nokogiri', '~> 1.6.0.rc1'
gem 'ffi', '~> 1.10'
gem 'watir-performance'
gem 'browserstack-webdriver'
gem 'rest-client', '~> 1.8'
gem 'influxdb', '~> 0.2.3'
